ystv/internal-site

lib/db/migrations/20240819162107_user_id_provider_constraint/migration.sql
=> Adds missing prisma migration

README.md
Updates the Read Me to add additional steps I needed to do to get a dev copy running
=> Update Read Me Setup Steps

Jenkinsfile
Apply database migrations to dev and prod automatically when deployed.
=> [INT-181] Update CI to automatically apply database schema migrations.

app/(authenticated)/layout.tsx, components/Breadcrumbs.tsx, components/Nav.tsx, styles/Nav.module.css
Tweaks and Updates the Navbar/Breadcrumbs
=> Nav Tweaks

Dockerfile, next.config.build.js, next.config.js
Include next.config.js in the docker build, this should fix issues with profile pictures not loading.
=> [INT-191] Fix images not loading

app/global-error.tsx, instrumentation.ts, next.config.build.js, next.config.js, package.json, yarn.lock
* Import configs from instrumentation file
* Add global-error.tsx
* Upgrade Sentry and add onRequestError
=> Fix Sentry configuration

server/index.ts
Dev is currently broken, I don't want it to be, much appreciated.
=> Replace slackApiConnection import with one that'll work after build.

app/(authenticated)/admin/page.tsx, app/(authenticated)/admin/positions/page.tsx, app/(authenticated)/admin/roles/page.tsx, app/(authenticated)/admin/users/[userID]/page.tsx, app/(authenticated)/admin/users/page.tsx, app/(authenticated)/calendar/[eventID]/page.tsx, app/(authenticated)/calendar/discover/page.tsx, app/(authenticated)/calendar/new/page.tsx, app/(authenticated)/feedback/page.tsx, app/(authenticated)/quotes/page.tsx, app/(authenticated)/user/me/page.tsx, app/(authenticated)/webcam/page.tsx, app/(authenticated)/wrapped/page.tsx, app/login/page.tsx, components/BackButton.tsx, components/PageInfo.tsx, components/SetClientData.tsx
As the title says, just add some titles to pages including event names on event pages.
I also added a back button to the feedback page lol.
=> [INT-199] Add titles to pages to differentiate tabs

lib/slack/slackApiConnection.ts
Which should stop it failing to come up with socket mode disabled
=> Tell Bolt to not listen on port 3000

app/login/google/callback/route.ts, app/login/google/route.ts, app/login/slack/callback/route.ts, app/login/slack/route.ts, components/SignoutButton/actions.ts, components/google/actions.ts, lib/auth/core.ts, lib/auth/server.ts, server/auth.ts
Main is once again broken, once again I'd like to fix it.
=> Move COOKIE_NAME to auth core and rename

app/(authenticated)/calendar/[eventID]/CheckWithTech.tsx
added the `<br>` love to the check with tech request descriptions and notes
=> [INT-208] Formatted check with tech request descriptions with line breaks

README.md, docs/contributing.md
@ben260 I may have missed some things from here that I told you, feel free to make any suggestions.
=> Add some basic docs for how to contribute to the project.

Dockerfile, Jenkinsfile
https://linear.app/ystv/issue/INT-XXX 
Changes Dev to internal-site, not calendar
Consistency
Magic
That's what dev is for
=> Change Dev to internal-site

Jenkinsfile
https://linear.app/ystv/issue/INT-XXX 
What I did before but for prod and preview
Why not
Same as last time
What's that?
=> Make prod and preview internal-site too

.env.example, README.md, app/(authenticated)/layout.tsx, app/layout.tsx, lib/env.ts, next.config.build.js, next.config.js
Read the title
Internal Site doesn't like being deadnamed
Just listened to what it wanted
It seems pretty happy now
=> Change more things over from [REDACTED] to internal-site

app/(authenticated)/calendar/new/schema.ts, app/login/page.tsx
Makes creating a recurring event optional and not mandatory (oops)
Mistake
Added .optional() on the zod schema
Yep definitely
=> Make recurring parts of event create form optional

components/navigation/Nav.tsx
Change the navbar to make use of the list of navlinks I put there and forgot about.
=> Make the navbar actually use the list of links

app/(authenticated)/admin/committee/teams/form.tsx, features/committee/teams.ts
https://linear.app/ystv/issue/INT-XXX 
Set fields in the database that are sent by the UI.
=> Fix committee team editing

app/(authenticated)/calendar/YSTVCalendar.tsx, app/(authenticated)/qr/page.tsx, components/navigation/Nav.tsx, package.json, yarn.lock
https://linear.app/ystv/issue/INT-223 
Add a page to generate YSTV branded QR codes.
The state of online QR code generators is a mess when it's a free thing to do.
Using https://www.npmjs.com/package/qr-code-styling and its next.js example
=> [INT-223] QR Code Generation

app/(authenticated)/admin/committee/positions/CommitteePositionCard.tsx, app/(authenticated)/admin/committee/positions/form.tsx, app/(authenticated)/admin/committee/positions/schema.ts, features/committee/positions.ts, features/committee/teams.ts, lib/db/migrations/20250924192113_add_committee_position_emails/migration.sql, lib/db/schema.prisma, lib/db/types/committeeposition.ts
https://linear.app/ystv/issue/INT-221 
Add committee position emails
So they can be viewed through the API for welcome site
Add a field to the DB and to the create/update forms
=> [INT-221] Add committee position emails

app/(authenticated)/user/me/PublicProfile.tsx, app/(authenticated)/user/me/actions.ts, features/people/schema.ts, features/people/users.ts, lib/db/migrations/20250925164557_make_it_woke/migration.sql, lib/db/schema.prisma, lib/db/types/user.ts
https://linear.app/ystv/issue/INT-230/make-it-woke 
Add ability for users to edit their pronouns
So that they can be pulled for welcome-site
A modal, state, and a dream.
=> [INT-230] Make it woke
