app/(authenticated)/user/[id]/page.tsx, app/login/google/callback/route.ts, components/Nav.tsx, components/SignoutButton/actions.ts, components/SignoutButton/index.tsx, components/google/GoogleLoginButton.tsx, components/google/actions.ts, lib/auth/server.ts
Google login and signing out in dev is currently broken, this should fix that. Google complained about the login_uri containing the redirect search parameter and so instead we use a cookie to store the redirect instead. Signing out would attempt to delete a cookie that was on the wrong domain, as it was not using `env.COOKIE_DOMAIN` which is used in dev.
=> Fix login logic and signout button

lib/env.ts
Fixes a bug in local versions of the site, in which .host includes the port in the cookie domain, and subsequently session cookies weren't being set, using .hostname fixes this
=> Fix setting of cookie domain to .hostname instead of .host

app/(authenticated)/layout.tsx, components/UserContext.tsx, lib/auth/google/index.ts, lib/auth/slack/index.ts, lib/db/migrations/20240904143009_remove_username/migration.sql, lib/db/schema.prisma, lib/db/types/user.ts
The user `username` field is unique, causing user creation to fail if the email prefix (anything before the "@") is used by another user. This made sense when only allowing google login from `@york.ac.uk` but causes issues now that login with slack is also available. The username field is unused everywhere except for Sentry, where it is used alongside the email it is derived from, and so is not needed.
=> [INT-177] Remove username from user

Jenkinsfile, app/(authenticated)/calendar/new/form.tsx, app/(authenticated)/calendar/page.tsx, app/api/public/events/route.ts, features/calendar/events.ts, features/calendar/permissions.ts, features/calendar/types.ts, lib/auth/permissions.ts
`/api/public/events` returns future events with the type "public". These can then be pulled and used on the welcome site for example. This allows events on the welcome site to be easily edited via the calendar.
=> Add an API endpoint for showing public events

Dockerfile, Jenkinsfile
Stop it from getting baked into the image (not ideal)
=> Pass in Sentry auth token as Docker secret rather than build arg

package.json
Ensure that the `certificates` folder exists before attempting to write files to it.
=> Create certificates folder on SSL generation

app/(authenticated)/(superuser)/admin/positions/page.tsx, app/(authenticated)/calendar/[eventID]/actions.ts, app/(authenticated)/calendar/[eventID]/signUpSheetActions.ts, app/(authenticated)/calendar/new/actions.ts, app/(authenticated)/calendar/new/page.tsx, app/(authenticated)/feedback/actions.ts, app/(authenticated)/quotes/actions.ts, app/(authenticated)/user/[id]/actions.ts, components/SignoutButton/actions.ts, components/google/actions.ts, components/slack/SlackUserInfo.tsx, features/positions/index.ts, lib/actions.ts, sentry.client.config.ts
Sentry doesn't do it automatically (https://github.com/getsentry/sentry-javascript/issues/9458)
=> Wrap all server actions in Sentry.withServerActionInstrumentation

app/(authenticated)/calendar/[eventID]/CheckWithTech.tsx, app/(authenticated)/calendar/[eventID]/SignupSheet.tsx, app/(authenticated)/calendar/[eventID]/actions.ts, app/(authenticated)/calendar/[eventID]/page.tsx
This fixes two issues with the #CheckWithTech form:
* The permissions check was using `canManage`, when it should have been `canManageAnySignUpSheet` (to allow any producer to submit it)
* Also change the prompt display check to `canManageAnySignUpSheet`
* There was no error handling (oops)
=> #CheckWithTech: Error handling and correct perms check

lib/slack/slackApiConnection.ts, package.json, server/index.ts, yarn.lock
This should hopefully reduce the logged messages from the slack connection restarting.
=> [INT-194] Only open slack socket on the persistent server

app/(authenticated)/calendar/[eventID]/page.tsx, app/(authenticated)/calendar/new/page.tsx, app/(authenticated)/calendar/page.tsx, app/(authenticated)/user/[id]/page.tsx
Should stop sentry spam with `Not logged in` errors, instead returning a redirect to /login
=> Replace calls to getCurrentUser in page components with mustGetCurrentUser

app/(authenticated)/calendar/[eventID]/EventActionsUI.tsx, app/(authenticated)/calendar/[eventID]/page.tsx, app/(authenticated)/calendar/new/form.tsx, components/FormFields.tsx
Make it more obvious that any changes will be made public immediately to people outside YSTV.
=> Add alert on public events to distinguish them

app/(authenticated)/calendar/[eventID]/SignupSheet.tsx, app/(authenticated)/calendar/[eventID]/signUpSheetActions.ts, features/calendar/signup_sheets.ts
Bit of a micro-optimisation: since by definition all crews on the same sheet have the same timings, either all of them have clashes or none of them do, so change the cache key to the sheet ID rather than the crew ID, and manually invalidate it upon signup/dropout.
=> Optimise clash checking by querying at the sheet level

app/(authenticated)/calendar/[eventID]/page.tsx
It's not useful to see it there, and could be confusing. Keep it on the new/edit forms where it's relevant.
=> Remove public event banner on event page

app/healthz/route.ts, features/lib/index.ts, server/index.ts, server/lib.ts
Do database connection monitoring slightly better
=> [INT-200] Check database connection on startup and on `/healthz` endpoint

components/WebcamView.tsx, features/calendar/check_with_tech.ts
The effect based approach was flawed in that React wouldn't re-run the effect if the `readystate` changed (even though it was in the list of dependencies, changes to stuff happening on refs doesn't trigger re-renders which therefore wouldn't trigger it to check for the effect dependency).
Replace it with an event-based approach.
(Also replaces `useDisclosure` with a `useState` to make the linter easier to appease.)
=> Make webcam loading spinners appear/disappear more reliably

app/(authenticated)/calendar/[eventID]/CheckWithTech.tsx, app/(authenticated)/calendar/[eventID]/actions.ts, app/(authenticated)/calendar/[eventID]/page.tsx, app/(authenticated)/user/me/page.tsx, components/slack/SlackLoginButton.tsx, features/calendar/check_with_tech.ts, features/calendar/check_with_tech_actions.ts, package.json, yarn.lock
Do this twofold:
* After submitting a request, if they don't have a Slack identity prompt to link
* If they still don't have one by the time we go to approve, show a message to that effect
=> #CheckWithTech: Better handle users without Slack

app/(authenticated)/calendar/[eventID]/CheckWithTech.tsx, app/(authenticated)/calendar/[eventID]/page.tsx, app/(authenticated)/user/me/page.tsx, app/login/google/callback/route.ts, app/login/google/route.ts, app/login/page.tsx, app/login/slack/callback/route.ts, app/login/slack/route.ts, components/SignoutButton/actions.ts, components/google/GoogleLoginButton.tsx, components/google/actions.ts, components/slack/SlackLoginButton.tsx, lib/auth/server.ts, lib/auth/slack/index.ts, server/auth.ts, tsconfig.json, tsconfig.server.json
Use the `/login/[provider]` endpoint to:
- Set a cookie for the redirect value
- Redirect to the regular login uri for the provider
This cookie is then read by the `/login/[provider]callback` route and redirects the user correctly after successful authentication
=> [INT-206] Rework post-login redirects

app/(authenticated)/calendar/[eventID]/actions.ts, app/(authenticated)/calendar/[eventID]/signUpSheetActions.ts, app/(authenticated)/calendar/new/actions.ts, lib/slack/errors.ts
Slack in prod is once again broken
I hate boltjs
=> Parse slack errors semi-properly

features/calendar/check_with_tech_actions.ts
This pull request includes updates to the `handleSlackViewEvent` and `_sendCWTFollowUpAndUpdateMessage` functions in the `features/calendar/check_with_tech_actions.ts` file to improve error handling and message updating logic.
Error handling improvements:
* Added a try-catch block around the Slack message update to log errors and ensure the requestor still receives a DM even if the update fails. [[1]](diffhunk://#diff-ba8b1057447e994f200a7de3ac31ace439de039b0dbf795e20ea3a7cefe9fdabR488) [[2]](diffhunk://#diff-ba8b1057447e994f200a7de3ac31ace439de039b0dbf795e20ea3a7cefe9fdabL515-R536)
Message updating logic enhancements:
* Moved the logic for finding the requestor's Slack identity and sending a DM to the requestor to after the channel message update. …
=> [INT-209] Update CheckWithTech Slack message even if requestor doesn't have Slack linked

flake.lock, lib/db/migrations/20241210194902_cwt_add_map/migration.sql, lib/db/schema.prisma
Changes the table name for the CheckWithTech schema.
I have OCD, it pains me to have only one table with uppercase letters in it.
Did some stuff lol.
That's what Dev is for.
=> Add map for CheckWithTech to prisma schema

app/(authenticated)/admin/positions/PositionView.tsx, app/(authenticated)/admin/roles/RoleView.tsx, app/(authenticated)/admin/users/UserView.tsx, app/(authenticated)/user/[id]/page.tsx, app/(authenticated)/user/me/page.tsx, features/calendar/events.ts, features/people/users.ts, lib/auth/permissions.ts, lib/searchParams/validate.ts, lib/searchParams/validateHook.ts
https://linear.app/ystv/issue/INT-215
* Adds a section to the user profile page to show a list of past events
* Allows admins to go to any user's profile page (with some current-user-specific things stubbed out)
Nice to reminisce on your productions. Also sometimes useful to see what someone's been involved in (e.g. award submissions).
Adds a `/user/[id]` route that renders the same page as `/user/me`, but for a given id, behind the new `People.ViewProfile.All` permission. On the user page, hides some bits unless the user is the current user.
Then, adds a listing of past events to a section on the page, behind a suspense boundary.
Also in the process I ran into issues with Next complaining that `lib/searchParams/validate.ts` was importing `usePathname` in non-client components, so I split …
=> [INT-215] Add past events list to profile, and allow admins to view other users' profiles

flake.nix
Don't set the prisma env variables on darwin in nix shells
It wasn't working before
If is darwin, don't set
It works now
=> [Nix Flake] Do not set prisma env vars on darwin

app/login/slack/route.ts
https://linear.app/ystv/issue/INT-218
Add slack team_id to the login url users are redirected to.
To hopefully stop users getting prompted to enter a workspace URL when linking their accounts.
I looked up how to on google.
Going to be honest, that's happening in dev.
=> [INT-218] Add slack team_id to the login url

app/login/slack/route.ts, lib/env.ts
https://linear.app/ystv/issue/INT-218 
Skips the workspace selection screen when signing in with slack
I did it wrong the last time
Change to a URL prefix instead of team_id in params
Replicating the URL in dev with its client ID works and skips workspace selection.
=> [INT-218] Skip slack workspace selection screen on login

lib/socket/server/signUpSheet.ts
https://linear.app/ystv/issue/INT-227 
Skip io import and access globalThis directly to allow signup updates to be sent
Linear reported the server failing to read properties when accessing io from an import
Access the io property of globalThis directly
Tested in PR preview, updates to crew sheets work as expected
=> [INT-227] Websocket message sends fail in production

app/(authenticated)/calendar/YSTVCalendar.tsx
Revert removal of spacer in header now the patch is fixed
Ben fixed the patch and the week names are back to how they were.
Just revert what I removed.
=> Revert removal of spacer in header now the patch is fixed

lib/slack/actions.ts
https://linear.app/ystv/issue/INT-162 
Unfurl links sent to slack with information about events.
So that users can get more information about events without having to click on the links.
Copied some code from Expedia.
=> [INT-162] Unfurl links sent to slack

features/calendar/events.ts, lib/env.ts
https://linear.app/ystv/issue/INT-235 
Fix timezone issues when creating events across the DST switch border
'twas brok
A bit of a hack to calculate the hours of difference between the client and server
It works in the preview
=> [INT-235] Fix timezone issues with recurring events
